# Default values for opensds csi plugin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: opensdsio/csiplugin:v0.5.4
# ImagePullPolicy: valid values are "IfNotPresent", "Never", and "Always"
imagePullPolicy: IfNotPresent
# ImageRestartPolicy: valid values are "Never", and "Always"
imageRestartPolicy: Never
# Please modify data fields in real environment
data:
  opensdsEndpoint: http://127.0.0.1:50040
  opensdsAuthStrategy: keystone
  osAuthURL: http://127.0.0.1/identity
  osUsername: admin
  osPassword: opensds@123
  osTenantName: admin
  osProjectName: admin
  osUserDomainId: default
  passwordEncrypter: aes
  enableEncrypted: F

# csiplugin-provisioner spec
csiplugin-provisioner:
  name: csi-provisioner-opensdsplugin
  replicaCount: 1
# csiplugin-attacher spec
csiplugin-attacher:
  name: csi-attacher-opensdsplugin
  replicaCount: 1
# csiplugin-nodeplugin spec
csiplugin-nodeplugin:
  name: csi-nodeplugin-opensdsplugin
  replicaCount: 1
# csiplugin-snapshotter spec
csiplugin-snapshotter:
  name: csi-snapshotter-opensdsplugin
  replicaCount: 1
